### ISSUE TITLE
Metacategory "Rare" Not working

### ISSUE THREAD

**Issue by VinsiesPlayer** [MADH95/JSONLoader#10]
I can get my rare card in normal card choices. Here is the text inside the jldr, incase it tells what is causing the problem:
_{
  "name": "InfestedSquirrel",
  "displayedName": "Infested squirrel",
  "description": "Like a squirrel, but infested by bees. Can't be sacrificed.",
  "metaCategories": [ "ChoiceNode", "TraderOffer", "Rare" ],
  "cardComplexity": "Advanced",
  "temple": "Nature",
  "baseAttack": 0,
  "baseHealth": 1,
  "tribes": [ "Squirrel" ],
  "abilities": [ "BeesOnHit" ],
  "traits": [ "Terrain" ],
  "texture": "InfestedSquirrel.png",
  "appearanceBehaviour": [ "RareCardBackground", "TerrainBackground", "TerrainLayout" ]
}_

**Comment by MADH95** [comment]
you shouldn't have "ChoiceNode" and "TraderOffer" if you have rare.

**Comment by VinsiesPlayer** [comment]
Ok. I thought that without them, it would just be a rare, but non-obtainable.
