### ISSUE TITLE
Frozen Within sigil seems to not work with editing existing creatures.

### ISSUE THREAD

**Issue by VinsiesPlayer** [MADH95/JSONLoader#12]
When this creature dies, it leaves behind an opossum, even though it has the iceCube field edited. I tried putting creatureWithin into fieldsToEdit, but that only caused an error in the BepInEx console.
{
  "name": "PackRat",
  "fieldsToEdit": [
      "displayedName",
      "description",
      "baseAttack",
      "baseHealth",
      "bloodCost",
      "abilities",
      "texture",
      "emissionTexture",
      "iceCube"
  ],
  "displayedName": "ToolBot",
  "description": "Gives you a random tool when used.",
  "baseAttack": 1,
  "baseHealth": 1,
  "bloodCost": 3,
  "abilities": [ "Brittle", "PermaDeath", "RandomConsumable", "IceCube" ],
"iceCube": {
    "creatureWithin": "Urayuli"
},
  "texture": "RatPack.png",
  "emissionTexture": "PatRack.png"
}

**Comment by MADH95** [comment]
There's been updates since this was posted, I assume it's resolved?
