### ISSUE TITLE
adds sigils multiple times

### ISSUE THREAD

**Issue by scrybeofteeth** [MADH95/JSONLoader#17]
using this with deck editor, and for some reason the sigils are being added several times over. in some cases, it's fine like three guard dog sigils. but with fecundity and the likes it's causing an issue.

{
	"name": "WolfCub",
    "modPrefix": "Base",
	"displayedName": "WolfCub",
	"baseAttack": 1,
	"baseHealth": 1,
	"bloodCost": 0,
	"bonesCost": 0,
	"abilities": [ "DrawCopy" ]
}
doing this causes the sigil to be applied twice.

**Comment by scrybeofteeth** [comment]
update: it's multiplying with every time I exit and enter, now it has 6 fecundity

**Comment by divisionbyz0rro** [comment]
This should be fixed in the latest push - give it a try and let me know.

**Comment by scrybeofteeth** [comment]
it's working perfectly now, thanks!
