### ISSUE TITLE
A way to add Starting Decks via json parsing.

### ISSUE THREAD

**Issue by BlindTheBoundDemon** [MADH95/JSONLoader#20]
Basically what is possible with cards now, I'd like to suggest making a similar thing for Kaycee's Mod custom starting decks.
Here's how I imagine the contents of an example json file would look like:

{
  "name": "ExampleDeck",
  "texture": "icon.png",
  "cards": [ "Coyote", "Urayuli", "Goat" ]
}

Of course any other potentially necessary fields would be added as well.

**Comment by MADH95** [comment]
This feature has been added
