### ISSUE TITLE
A way to change the card background to a custom one.

### ISSUE THREAD

**Issue by BlindTheBoundDemon** [MADH95/JSONLoader#24]
Could be something like:

`"backgroundTexture": "background.png"`

Alternatively it could be merged into `appearanceBehavior`
Depends on which one is easier to do or easier to use...

**Comment by SaxbyMod** [comment]
So https://inscryption.thunderstore.io/package/SpecialAPI/Configurable_Emissions_and_Backgrounds/ again its here
