### ISSUE TITLE
A parameter to force emissions.

### ISSUE THREAD

**Issue by BlindTheBoundDemon** [MADH95/JSONLoader#25]
Yes, me again. This time with a slightly more QoL suggestion but I think it would be quite useful.
Here's my suggested syntax (as a boolean):

`"forceEmission": true`

This would basically give the card the effect that Greater Smoke has. That is having emission layer enabled regardless of the card having added sigils or not.

**Comment by SaxbyMod** [comment]
Its in a Mod by SPAPI btw https://inscryption.thunderstore.io/package/SpecialAPI/Configurable_Emissions_and_Backgrounds/
