### ISSUE TITLE
Can be Closed this is existant now.

### ISSUE THREAD

**Issue by SaxbyMod** [MADH95/JSONLoader#39]
some sort of json that can load a custom encounter
Like
{ 
  "Encounters: [
      {
      "Phase 1": [
{ 
"Urayuli",
"Urayuli"
}]
}]
} 
or something similar

**Comment by IngoHHacks** [comment]
We used to have that, but support for it got dropped after the rewrite.

**Comment by SaxbyMod** [comment]
Exists Now
