### ISSUE TITLE
Allow for custom property settings for Custom Abilities

### ISSUE THREAD

**Issue by julian-perge** [MADH95/JSONLoader#5]
With the advent of new custom abilities, mods are now incorporating custom configurations inside .cfg files, such as SigilADay, JSONLoader itself, and many more to come in the future.

JSONLoader being the defacto mod for creating custom cards and modifying existing ones, adding additional properties to search for in the "customAbilities" array objects would remove the need for these .cfg files.

For example, for my SigilADay ability `Evolve Randomly`, allows adding cards with specified evolutions to turn into.

The example .jldr layout would look something like this:
```
{
  "name": "Geck",
  "fieldsToEdit": [
    "customAbilities"
  ],
  "customAbilities": [
    {
      "name": "Evolve Randomly",
      "GUID": "julianperge.inscryption.sigiladay",
      "properties": [{
        "cardsToEvolveInto": "Skunk,Shark",
        "methodToCall": "Evolve.Randomly.AddCardToDictionary"
      }]
    }
  ]
}
```

**Comment by MADH95** [comment]
This is definitely an ongoing consideration for the future of jsonloader, but would function much better with the support of the API.

**Comment by MADH95** [comment]
I believe this is resolved in the up to date version, can you confirm?

**Comment by SaxbyMod** [comment]
> I believe this is resolved in the up to date version, can you confirm?

Yes it is its called `Extended Properties`
