### ISSUE TITLE
can cards created be used in Kaycee's Mod?

### ISSUE THREAD

**Issue by SkyStreet** [MADH95/JSONLoader#64]
Maybe a bit trivial…… But I didn't find a related claim or gainsay. Moreover, what would "ChoiceNode" in "Meta Categories" look like? Will there be a pop-up choice option in the game?

**Comment by SaxbyMod** [comment]
If it has those it they will pop up in both trader and any choice node(Except Rare) and for both KCM And ACT 1 as long as temple is set to nature
